spring:
  application:
    name: todo application
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: user
    password: "password"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:9786/user_db?autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Africa/Harare&rewriteBatchedStatements=true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.xxx.com
    port: 587
    password: xxxxx
    username: xxxxxx
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

server:
  port: 9100
jwt:
  secret: "82F413F4428472B4B6250645367566B5970404E635266556A586E32723575387"
system:
  name: JWT Based User Management

email:
  origin:
    sender: cbcv@xxx.com

file-storage:
  base-path: ./


access:
  token:
    expirationTimeInSec: 600


refresh:
  token:
    expirationTimeInSec: 60
