version: "3.8"

services:

  userdb:
    image: mysql:8
    container_name: userdb
    hostname: userdb
    ports:
      - 9786:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=user_db
    volumes:
      - ./data:/var/lib/mysql/





